# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: this.rob.blog
email: robstevenson000@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A place to document and share my learnings. Mainly so I can go back and copy paste when I forget how to do something ;)
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: thisdotrob
github_username:  thisdotrob

# Build settings
markdown: kramdown
